### PR TITLE
Add fossa analysis step to CI

### PR DESCRIPTION
**Pull request by bspammer**
[As requested here](https://eatmarshmallows.slack.com/archives/C8J3F9PN1/p1667389007431219?thread_ts=1667385398.687619&cid=C8J3F9PN1), this should run the fossa tool on every merge to main. We need to install the fossa CLI, and yq, then we use the FOSSA_API_KEY organization secret to run the analysis and upload it.

### CODE REVIEW

**Comment by fleonard** [comment]
@bspammer have you had a look at [these](https://github.com/fossas/fossa-action) by any chance? Wondering if we might just use their own actions?

**Comment by bspammer** [comment]
@fleonard Nice! No I just assumed they hadn't published an action, that should simplify it somewhat.

**Comment by fleonard** [comment]
@bspammer yeah it will also be much better cause if we just use the latest everything they update will be automatically picked up

**Comment by bspammer** [comment]
@fleonard actually looking again this action doesn't have any way of specifying the team, nor of specifying the security policy. We would need to add `opslevel.yaml` to the repo to make this work. It's up to you what you'd prefer really.

**Comment by fleonard** [comment]
@bspammer we already a `yaml` file for `opslevel` so shouldn't be an issue to add one for fossa

**Comment by bspammer** [comment]
@fleonard Ok sure, it will make it more inconsistent with the other repos but I guess that ship has sailed already 😁

**Review by fleonard — APPROVED** [review]

**Pull request merged**
