### PR TITLE
Feat: export useBodyScrollLock hook

### PR DESCRIPTION
**Pull request by matdiak**
## What does this do?
Exports useBodyScrollLock so it can be used outside of smores

### CODE REVIEW

**Comment by DeadEnglish** [comment]
Now that we're using this as an export, could we move this to the `hooks` folder rather than nested inside the `Modal` component.

**Comment by matdiak** [comment]
@DeadEnglish moved it to utils with other hooks unless you think creating a hook dir?

**Comment by DeadEnglish** [comment]
There should already be a [hook directory](https://github.com/marshmallow-insurance/smores-react/tree/main/src/hooks) in the `src` folder 😄

**Comment by matdiak** [comment]
@DeadEnglish oh ye, somethow I didn't see it

**Review by DeadEnglish — APPROVED** [review]

**Pull request merged**
